name: CI
permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Check Buildifier formatting
        run: bazel run //:buildifier_check
