name: Code Coverage
permissions: read-all

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install clang/llvm
        run: sudo apt-get install -y clang

      # Setup Bazel (using Bazelisk is recommended for version management)
      - name: Mount Bazel Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Run Tests with Coverage (with clang)
        env:
          CC: clang
          CXX: clang++
        run: |
          bazel coverage --config=coverage //...

      - name: Upload to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: bazel-out/_coverage/_coverage_report.dat
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
