name: Code Coverage
permissions: read-all

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Install clang/llvm
        run: sudo apt-get install -y clang

      # Setup Bazel (using Bazelisk is recommended for version management)
      - name: Mount Bazel Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Run Tests with Coverage (with clang)
        env:
          CC: clang
          CXX: clang++
        run: |
          bazel coverage --config=coverage //...

      - name: Upload to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: bazel-out/_coverage/_coverage_report.dat
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
