name: Super-Linter
permissions: read-all

# Run this workflow on Pull Requests and Pushes to the main branch
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          # Full git history is needed to check changed files
          fetch-depth: 0
          persist-credentials: false

      # Step 2: Run Super-Linter
      - name: Lint Code Base
        uses: super-linter/super-linter@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 # v8
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set your default branch (usually main or master)
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
