name: Super-Linter

# Run this workflow on Pull Requests and Pushes to the main branch
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
    workflow_dispatch:
      inputs:
        validate_all_codebase:
          description: 'Validate All Codebase'
          required: false
          default: true 
        type: boolean

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to check changed files
          fetch-depth: 0

      # Step 2: Run Super-Linter
      - name: Lint Code Base
        uses: super-linter/super-linter@v6
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set your default branch (usually main or master)
          DEFAULT_BRANCH: main
          # If 'inputs' exists (manual run), use that value. 
          # If 'inputs' is empty (automatic run), default to false.
          # validates all code in the repo on a push, but only changed files on a PR
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase || false }}