name: Super-Linter
permissions: read-all

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          # Full git history is needed to check changed files
          fetch-depth: 0
          persist-credentials: false

      # Step 2: Run Super-Linter
      - name: Lint Code Base
        uses: super-linter/super-linter@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set your default branch (usually main or master)
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
